### ISSUE TITLE
pyclustercheck not properly checking the cluster node

### ISSUE THREAD

**Issue by grypyrg** [Oneiroi/clustercheck#12] opened 2015-06-12 15:19 UTC
pyclustercheck seems to mark nodes as down and up all the time when nodes are down. It lies!

Did anybody of you notice this already?

Yes I know I don't have a full test case, but I wanted to track it here first. I'll check this when I do some tests again in the future.  :)

**Comment by Oneiroi** [comment] 2015-06-12 15:24
There has been some mention of the `SimpleHTTPServer` version leading to lock up but I've not been able to recreate the issue, the `twisted` python version however as per blog post: https://www.percona.com/blog/2014/05/16/benchmark-simplehttpserver-vs-pyclustercheck-twisted-implementation/ is by far the more stable version.

The issue is twisted it not a standard library as such the "bundled" version is not the `twisted` variant and relaint on `SimpleHTTPServer`

Can you indicate which version you are using? and I'll leave this open as/when a test case appears (I've been unsuccessful in creating one :( )

**Comment by Oneiroi** [comment] 2015-08-21 14:29
closing this for now, @grypyrg if you have a test case please let me know and we can re-open an issue.

**Closed by Oneiroi** 2015-08-21 14:29 UTC

**Comment by grypyrg** [comment] 2015-09-15 17:57
So easy to reproduce:

- stop mysql
- do clustercheck with caching enabled.
- do clustercheck with caching enabled.

and look at the weird results!

**Comment by grypyrg** [comment] 2015-09-15 18:00
```
[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node state could not be retrieved.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node state could not be retrieved.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node state could not be retrieved.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node is synced.[root@pxc1 ~]# curl localhost:8000
Percona XtraDB Cluster Node state could not be retrieved.[root@pxc1 ~]# 
```

Basically, every time cache time is expired, the clustercheck woudl fail, all cache retrievals would return 'synced'

**Comment by UnixRonin** [comment] 2016-12-02 23:27
You know, it's been noted that the pyclustercheck-twisted implementation is dependent upon python-twisted which is not a "standard" package in typical distributions, as though this is a strike against it.  I think it should be pointed out that the non-twisted implementation is dependent upon MySQL-python, which is ALSO not a "standard" package.  So both implementations require non-standard packages to be pulled in.

For that matter, even the shell-script clustercheck requires xinetd, which is not a default installed not really an important issue.  All three clustercheck implementations have additional package dependencies which are not normally installed by default.  It's only a question of which ones(s).
